name: "Azure Blob storage Tool"
description: "Update ExpiresAt of a blob in Azure Blob storage"
author: "Bo-Yi Wu"
inputs:
  accountName:
    description: "Account name of Azure Blob storage"
    required: true
  accountKey:
    description: "Account key of Azure Blob storage"
    required: true
  containerName:
    description: "Container name of Azure Blob storage"
    required: true
  blobName:
    description: "Blob name of Azure Blob storage"
    required: true
  duration:
    description: "ExpiresAt duration"
    default: "24h"

runs:
  using: "docker"
  image: "Dockerfile"

branding:
  icon: "cloud"
  color: "blue"
