name: "Azure Blob storage Tool"
description: "Update ExpiresAt of a blob in Azure Blob storage"
author: "Bo-Yi Wu"
inputs:
  account_name:
    description: "Account name of Azure Blob storage"
    required: true
  account_key:
    description: "Account key of Azure Blob storage"
    required: true
  container_name:
    description: "Container name of Azure Blob storage"
    required: true
  blob_name:
    description: "Blob name of Azure Blob storage"
    required: true
  duration:
    description: "ExpiresAt duration"
    default: "1h"

runs:
  using: "docker"
  image: "Dockerfile"

branding:
  icon: "cloud"
  color: "blue"
